language: java
install: true


dist: trusty
jdk:
  - openjdk13
  - openjdk-8


matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
    
    

script:
  - ./gradlew --continue clean build
