language: java
install: true


dist: trusty
jdk:
  - oraclejdk13
  - oraclejdk-ea


matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
    

script:
  - ./gradlew --continue clean build --scan -s -p modules/
 
