language: java
install: true


dist: trusty
jdk:
  - openjdk11
  - openjdk8
  - oraclejdk8
  - oraclejdk11


matrix:
  allow_failures:
    - jdk: openjdk8

branches:
  only:
  - master
    
    

script:
  - ./gradlew --continue clean build --scan -s -p modules/
