language: java
install: true


dist: trusty
jdk:
  - oraclejdk13


matrix:
  allow_failures:
    - jdk: - oraclejdk13

branches:
  only:
  - master
    

script:
  - ./gradlew --continue clean build --scan -s -p modules/
 
